#!/usr/bin/env bash
# a morons implementation of traceroute

addr=${1}

for k in {1..99}; do
  res=$(ping -t ${k} -c1 ${addr} -W3)
  res=(${res})

  case ${res[@]} in
  *"exceeded"* | *"0 received"*)
    (( hopcount++ ))
    [[ ${res[@]} == *"exceeded"* ]] && {
      printf "Hop %i:\t%s\n" ${hopcount} ${res[8]}
      continue
    }
    printf "Hop %i:\t???\n" ${hopcount}
  ;;
  *icmp_seq*) break    ;;
  *)          continue ;;
  esac
done
